Add home screen
Co-Epi/app-android pull request #17
Opened 2020-03-28 23:43 UTC by mellowgeek

First cut at removing bottom navigation and adding the home screen.

2020-03-29 22:42 UTC, ivnsch requested changes
Since there are no tabs anymore, can you add an entry point to the BLE fragment in the debug view?

2020-03-29 22:42 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/home/HomeFragment.kt
> +import kotlinx.android.synthetic.main.fragment_home.*
Don't use kotlinx. We use View Binding. See other fragments.

2020-03-29 22:42 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/home/HomeFragment.kt
> +        check_in.setOnClickListener {
Put this in `onCreateView`, see other fragments

2020-03-29 22:42 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/home/HomeFragment.kt
> +            findNavController().navigate(action)
Navigation should be in view model, see existing view models

2020-03-29 22:42 UTC, i-schuetz commented on app/src/main/res/layout/fragment_home.xml
> +            <RelativeLayout
Use `ConstraintLayout`. It pretty much replaces `RelativeLayout`.

2020-03-29 22:42 UTC, i-schuetz commented on app/src/main/res/layout/fragment_home.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
You can use a vertical `LinearLayout`.

2020-03-29 22:42 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/container/TabsContainerFragment.kt
>  class TabsContainerFragment : Fragment() {
Rename it in `ContainerFragment`. Probably the class and navigation root should be removed, but let's keep it for now.

2020-03-30 01:52 UTC, mellowgeek commented
> Since there are no tabs anymore, can you add an entry point to the BLE fragment in the debug view?

Added a BLE button to the debug log screen.

2020-03-30 20:50 UTC, ivnsch approved these changes

2020-03-30 20:50 UTC, merged