New ux date since earlist symptoms
Co-Epi/app-android pull request #175
Opened 2020-05-18 14:44 UTC by Joshua-McCord

Removed Earliest Symptom as an ID and is instead just a step/input in the process. Cleaned up some of the code addressed.

2020-05-18 15:25 UTC, Joshua-McCord commented
Cleared up Merge Conflicts with updated Develop. Should just require review.

2020-05-18 20:05 UTC, i-schuetz commented
Thanks for the follow up! Earliest symptom seems to be still in the ids though.

2020-05-18 20:05 UTC, ivnsch requested changes
Thanks for the follow up! Earliest symptom seems to be still in the ids though.

2020-05-19 16:54 UTC, ivnsch approved these changes

2020-05-19 17:31 UTC, merged