New UX Onboarding
Co-Epi/app-android pull request #179
Opened 2020-05-20 17:27 UTC by lagaren

This PR covers the implementation of the new UX for the onboarding screen. 

Note: As of right now I can't seem to find a way to easily retrieve a formatted string from Android resources w/o API level 24. As a result, some of the text strings in the onboarding menus don't have specific words bolded like they do in the Figma. I was advised to push this up regardless and we could address that later.

Thanks

2020-05-21 14:54 UTC, ivnsch requested changes

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/onboarding/OnboardingFragment.kt
> +        const val SMALL_CARD = 0
Define these in the adapter, since they're needed only there.

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/onboarding/OnboardingAdapter.kt
> +            SMALL_CARD -> LayoutInflater.from(parent.context).inflate(R.layout.card_onboarding_small, parent, false)
You can use static import here (alt+enter or opt+enter and "add import...) both on `from` and the layout name, to make this a bit shorter.

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/onboarding/OnboardingAdapter.kt
> +            else -> LayoutInflater.from(parent.context).inflate(R.layout.card_onboarding_unknown, parent, false)
The only part that varies in the 3 cases is the layout, so you can do `...inflate(when {...}...)` or `when {...}.let { ...inflate(it...) }`

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/onboarding/OnboardingAdapter.kt
> +    override fun getItemCount(): Int = data.size
If you use `ListAdapter` (see other adapters), you don't have to implement these.

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/onboarding/OnboardingCard.kt
> +        val order: Int
I'd put `order` in all the cards. This seems to make assumptions about where the cards are based on style, which isn't good.

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/onboarding/OnboardingFragment.kt
> +import kotlinx.android.synthetic.main.fragment_onboarding.*
We don't use `kotlinx`. Use `ViewBinding` (see other fragments).

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/onboarding/OnboardingFragment.kt
> +    private val compositeDisposable = CompositeDisposable()
We don't use disposables/rx in the fragments, but convert to `LiveData` in the view models. See other places.

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/onboarding/OnboardingFragment.kt
> +                                )
Logic should be in the view model. Add separate observables / live data there for navigating to scroll position, opening activity, etc. Fragment should have only the minimum to wire with the UI.

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/onboarding/OnboardingFragment.kt
> +            context.resources.getString(string.onboarding_card_title_1),
The cards (i.e. view data) should be also generated in the model and exposed via `LiveData`. We've a `Resources` dependency which with you can retrieve strings there. You can also use static imports for the string ids, to get rid of the `string.`

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/onboarding/OnboardingFragment.kt
> +        private const val FAQ_WEBPAGE_URL = "https://www.coepi.org/faq/"
I'd put these in `strings.xml`.

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/onboarding/binders/LargeOnboardingCardBinder.kt
> +        onboardingCard as LargeOnboardingCard
Let's put the force-casts in the adapter, so they're all together and it's consistent with the rest of the code. Pass `LargeOnboardingCard` to binder (also in the others)

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/onboarding/binders/LargeOnboardingCardBinder.kt
> +import kotlinx.android.synthetic.main.card_onboarding_large.view.*
Use `ViewBinding`

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/onboarding/binders/LargeOnboardingCardBinder.kt
> +            onboardingEventSubject.onNext(OnboardingClickEvent.JoinClicked)
You can use static imports so it's only `JoinClicked` (also in the others)

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/onboarding/binders/OnboardingCardBinder.kt
> +interface OnboardingCardBinder {
Do we really need this abstraction? I personally would just use directly the classes. Then you also can pass the concrete card model class without having to add generics here.

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/onboarding/binders/SmallOnboardingCardBinder.kt
> +            0 -> itemView.progress_icon_1.setImageResource(R.drawable.stepper_icon_selected)
Add the image resource to the view data in the view model. This is again too much logic for the view. View data should be "ready to consume".

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/res/layout/card_onboarding_large.xml
> +        app:layout_constraintStart_toStartOf="parent">
Why do we need 2x constraint layout?

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/res/layout/card_onboarding_large.xml
> +        android:layout_width="match_parent"
Should be `0dp` (also in other places).

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/res/layout/fragment_onboarding.xml
> +            android:nestedScrollingEnabled="false"
Why do we need this?

2020-05-21 14:54 UTC, i-schuetz commented on app/src/main/res/layout/fragment_onboarding.xml
>              android:layout_width="match_parent"
`0dp`

2020-05-29 08:20 UTC, i-schuetz commented
Any blockers here?

2020-05-29 13:54 UTC, lagaren commented
No blockers. I'm making the changes you suggested now. I have another project that I work on that have eaten up most of my time this week. Sorry about that.

2020-05-29 15:59 UTC, i-schuetz commented
All good! Just checking status.

2020-06-02 17:38 UTC, i-schuetz commented
@lagaren I've time, should I take this over?

2020-06-02 17:53 UTC, lagaren commented
@i-schuetz Honestly at this point that might be best. I've just now had a deadline moved up on me for my other project and some relief would be very welcome.

2020-06-03 17:35 UTC, ivnsch approved these changes

2020-06-03 17:42 UTC, merged