Swipe to delete exposure alerts functionality added
Co-Epi/app-android pull request #203
Opened 2020-06-05 11:46 UTC by laurenipsum365

https://github.com/Co-Epi/app-android/issues/180

Added swipe to delete exposure alert logic to Exposure Alerts screen.

2020-06-05 16:43 UTC, i-schuetz commented
Looking good! I noticed some issues while testing (I mocked some fake alerts in `AlertsRepo`, with a `BehaviorSubject`):
- After the alert is swiped out, it appears shortly again before is removed from the list
- There's a `sorted()` in `AlertsViewModel` on the alerts. This is an Rx operator that is not doing what we need here.
- Connected with point above, are you using the contact time to sort and group (showing the header) the alerts? This may not be the case.

2020-06-05 16:44 UTC, ivnsch requested changes
Looking good! I noticed some issues while testing (I mocked some fake alerts in `AlertsRepo`, with a `BehaviorSubject`):

- After the alert is swiped out, it appears shortly again before it's removed from the list
- There's a `sorted()` in `AlertsViewModel` on the alerts. This is an Rx operator that is not doing what we need here.
- Connected with point above, are you using the contact time to sort and group (showing the header) the alerts? This may not be the case.

2020-06-09 04:28 UTC, laurenipsum365 commented
@i-schuetz added new Exposure alerts info screen, and I believe I fixed the sorting problem by adding a compareTo method inside the Alert class and using that in the mapping function inside the VM.

2020-06-09 16:03 UTC, ivnsch approved these changes

2020-06-09 16:18 UTC, merged