Bluetooth request info
Co-Epi/app-android pull request #246
Opened 2020-06-17 20:44 UTC by Joshua-McCord

When installing the app for the first first time (when there are no permissions granted), the user will be shown a dialogue explaining the Application's use of Bluetooth. 

![device-2020-06-17-155956](https://user-images.githubusercontent.com/43547244/84946024-05703e80-b0b6-11ea-886d-25e95c36c889.png)

2020-06-18 14:43 UTC, i-schuetz commented
https://developer.android.com/training/permissions/requesting#explain ?

2020-06-19 20:04 UTC, mellowgeek commented
With the update to include the rationale dialog, I think we should change the buttons to be more clear that you're going to prompt for permissions in that dialog. The two examples I've seen are either give a single option that says "OK", or stick with the two options and instead of "Allow/Don't Allow", use something like "Retry/I'm sure"

2020-06-22 20:40 UTC, ivnsch requested changes
(Slack)

2020-06-23 20:11 UTC, i-schuetz commented on app/src/main/java/org/coepi/android/ui/onboarding/OnboardingPermissionsChecker.kt
> +            shouldShowRequestPermissionRationale(activity, ACCESS_COARSE_LOCATION) ->
Why only for `ACCESS_COARSE_LOCATION`?

2020-06-23 20:15 UTC, i-schuetz commented
As per https://github.com/Co-Epi/app-android/issues/239#issuecomment-647987762, would it make sense to request the permissions after the onboarding?

2020-06-27 21:23 UTC, merged